import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ตรวจสอบการชำระเงิน ออเดอร์ลูกค้า PWS | PromotionWatchShop",
  description: "Generated by PNinitz",
};

export default function AddProductLayout({ children }) {
    return <html lang="en">
    <body className={inter.className}>{children}</body>
    </html>
  }